version: "3.2"

services:
  redis:
    image: redis:6
    hostname: redis
    container_name: upwork-scraper-redis
    ports:
      - 6379:6379
  database:
    image: postgres:12
    hostname: postgres
    container_name: upwork-scraper-postgres
    environment:
      - POSTGRES_DB=upworkscraper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
